name: Publish ${package_name} to PyPI / GitHub

on:
  push:
    tags:
      - "v*"
    branches:
      - main
    release:
      types: [published]

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*

      - name: Create tag in public repository
        run: |
          git tag -a v1.5
          git push origin --tags 

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.5
          release_name: Release v1.5
          draft: false
          prerelease: false