name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "type: feature"
  default: patch
template:
  ## What's changed

  $CHANGES