name: test calculator

on:
  push:
    branches: [ "main", "release-0.1", "develop" ]

permissions:
  contents: read

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Five tests for binary search using -PYTEST-
      run: |
        pytest ./tests/test_add_sub_mult_div.py
